name: Convert Draw.io to PNG

on:
  push:
    paths:
      - '**.drawio'  # Aciona o workflow sempre que um arquivo .drawio for alterado
  workflow_dispatch:  # Permite execução manual

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Draw.io CLI
        run: |
          sudo apt update && sudo apt install drawio

      - name: Converter Draw.io para PNG
        run: |
          for file in $(find . -name "*.drawio"); do
            output="${file%.drawio}.png"
            drawio -x -f png -o "$output" "$file"
          done

      - name: Commit e Push das Imagens Convertidas
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Convert Draw.io files to PNG [Automated]" || echo "Nenhuma mudança para commit"
          git push
